export const stripeCurrencies = [
  { label: 'USD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'AED', currencySymbol: 'د.إ', multiplier: 100, type: 'STRIPE' },
  { label: 'AFN', currencySymbol: '؋', multiplier: 100, type: 'STRIPE' },
  { label: 'ALL', currencySymbol: 'L', multiplier: 100, type: 'STRIPE' },
  { label: 'AMD', currencySymbol: '֏', multiplier: 100, type: 'STRIPE' },
  { label: 'ANG', currencySymbol: 'ƒ', multiplier: 100, type: 'STRIPE' },
  { label: 'AOA', currencySymbol: 'Kz', multiplier: 100, type: 'STRIPE' },
  { label: 'ARS', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'AUD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'AWG', currencySymbol: 'ƒ', multiplier: 100, type: 'STRIPE' },
  { label: 'AZN', currencySymbol: '₼', multiplier: 100, type: 'STRIPE' },
  { label: 'BAM', currencySymbol: 'BAM', multiplier: 100, type: 'STRIPE' },
  { label: 'BBD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'BDT', currencySymbol: '৳', multiplier: 100, type: 'STRIPE' },
  { label: 'BGN', currencySymbol: 'лв', multiplier: 100, type: 'STRIPE' },
  { label: 'BIF', currencySymbol: 'Fr', multiplier: 1, type: 'STRIPE' },
  { label: 'BMD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'BND', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'BOB', currencySymbol: 'Bs.', multiplier: 100, type: 'STRIPE' },
  { label: 'BRL', currencySymbol: 'R$', multiplier: 100, type: 'STRIPE' },
  { label: 'BSD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'BWP', currencySymbol: 'P', multiplier: 100, type: 'STRIPE' },
  { label: 'BZD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'CAD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'CDF', currencySymbol: 'Fr', multiplier: 100, type: 'STRIPE' },
  { label: 'CHF', currencySymbol: 'Fr', multiplier: 100, type: 'STRIPE' },
  { label: 'CLP', currencySymbol: '$', multiplier: 1, type: 'STRIPE' },
  { label: 'CNY', currencySymbol: '¥', multiplier: 100, type: 'STRIPE' },
  { label: 'COP', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'CRC', currencySymbol: '₡', multiplier: 100, type: 'STRIPE' },
  { label: 'CVE', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'CZK', currencySymbol: 'Kč', multiplier: 100, type: 'STRIPE' },
  { label: 'DJF', currencySymbol: 'Fr', multiplier: 1, type: 'STRIPE' },
  { label: 'DKK', currencySymbol: 'kr', multiplier: 100, type: 'STRIPE' },
  { label: 'DOP', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'DZD', currencySymbol: 'د.ج', multiplier: 100, type: 'STRIPE' },
  { label: 'EGP', currencySymbol: '£', multiplier: 100, type: 'STRIPE' },
  { label: 'ETB', currencySymbol: 'Br', multiplier: 100, type: 'STRIPE' },
  { label: 'EUR', currencySymbol: '€', multiplier: 100, type: 'STRIPE' },
  { label: 'FJD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'FKP', currencySymbol: '£', multiplier: 100, type: 'STRIPE' },
  { label: 'GBP', currencySymbol: '£', multiplier: 100, type: 'STRIPE' },
  { label: 'GEL', currencySymbol: '₾', multiplier: 100, type: 'STRIPE' },
  { label: 'GIP', currencySymbol: '£', multiplier: 100, type: 'STRIPE' },
  { label: 'GMD', currencySymbol: 'D', multiplier: 100, type: 'STRIPE' },
  { label: 'GNF', currencySymbol: 'Fr', multiplier: 1, type: 'STRIPE' },
  { label: 'GTQ', currencySymbol: 'Q', multiplier: 100, type: 'STRIPE' },
  { label: 'GYD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'HKD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'HNL', currencySymbol: 'L', multiplier: 100, type: 'STRIPE' },
  { label: 'HRK', currencySymbol: 'kn', multiplier: 100, type: 'STRIPE' },
  { label: 'HTG', currencySymbol: 'G', multiplier: 100, type: 'STRIPE' },
  { label: 'HUF', currencySymbol: 'Ft', multiplier: 100, type: 'STRIPE' },
  { label: 'IDR', currencySymbol: 'Rp', multiplier: 100, type: 'STRIPE' },
  { label: 'ILS', currencySymbol: 'ع.د', multiplier: 100, type: 'STRIPE' },
  { label: 'INR', currencySymbol: '₹', multiplier: 100, type: 'STRIPE' },
  { label: 'ISK', currencySymbol: 'kr', multiplier: 100, type: 'STRIPE' },
  { label: 'JMD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'JPY', currencySymbol: '¥', multiplier: 1, type: 'STRIPE' },
  { label: 'KES', currencySymbol: 'Sh', multiplier: 100, type: 'STRIPE' },
  { label: 'KGS', currencySymbol: 'с', multiplier: 100, type: 'STRIPE' },
  { label: 'KHR', currencySymbol: '៛', multiplier: 100, type: 'STRIPE' },
  { label: 'KMF', currencySymbol: 'Fr', multiplier: 1, type: 'STRIPE' },
  { label: 'KRW', currencySymbol: '₩', multiplier: 1, type: 'STRIPE' },
  { label: 'KYD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'KZT', currencySymbol: '₸', multiplier: 100, type: 'STRIPE' },
  { label: 'LAK', currencySymbol: '₭', multiplier: 100, type: 'STRIPE' },
  { label: 'LBP', currencySymbol: 'ل.ل', multiplier: 100, type: 'STRIPE' },
  { label: 'LKR', currencySymbol: 'Rs', multiplier: 100, type: 'STRIPE' },
  { label: 'LRD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'LSL', currencySymbol: 'L', multiplier: 100, type: 'STRIPE' },
  { label: 'MAD', currencySymbol: 'د.م.', multiplier: 100, type: 'STRIPE' },
  { label: 'MDL', currencySymbol: 'L', multiplier: 100, type: 'STRIPE' },
  { label: 'MGA', currencySymbol: 'Ar', multiplier: 1, type: 'STRIPE' },
  { label: 'MKD', currencySymbol: 'ден', multiplier: 100, type: 'STRIPE' },
  { label: 'MMK', currencySymbol: 'Ks', multiplier: 100, type: 'STRIPE' },
  { label: 'MNT', currencySymbol: '₮', multiplier: 100, type: 'STRIPE' },
  { label: 'MOP', currencySymbol: 'P', multiplier: 100, type: 'STRIPE' },
  { label: 'MRO', currencySymbol: 'UM', multiplier: 100, type: 'STRIPE' },
  { label: 'MUR', currencySymbol: '₨', multiplier: 100, type: 'STRIPE' },
  { label: 'MVR', currencySymbol: '.ރ', multiplier: 100, type: 'STRIPE' },
  { label: 'MWK', currencySymbol: 'MK', multiplier: 100, type: 'STRIPE' },
  { label: 'MXN', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'MYR', currencySymbol: 'RM', multiplier: 100, type: 'STRIPE' },
  { label: 'MZN', currencySymbol: 'MT', multiplier: 100, type: 'STRIPE' },
  { label: 'NAD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'NGN', currencySymbol: '₦', multiplier: 100, type: 'STRIPE' },
  { label: 'NIO', currencySymbol: 'C$', multiplier: 100, type: 'STRIPE' },
  { label: 'NOK', currencySymbol: 'kr', multiplier: 100, type: 'STRIPE' },
  { label: 'NPR', currencySymbol: '₨', multiplier: 100, type: 'STRIPE' },
  { label: 'NZD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'PAB', currencySymbol: 'B/.', multiplier: 100, type: 'STRIPE' },
  { label: 'PEN', currencySymbol: 'S/.', multiplier: 100, type: 'STRIPE' },
  { label: 'PGK', currencySymbol: 'K', multiplier: 100, type: 'STRIPE' },
  { label: 'PHP', currencySymbol: '₱', multiplier: 100, type: 'STRIPE' },
  { label: 'PKR', currencySymbol: '₨', multiplier: 100, type: 'STRIPE' },
  { label: 'PLN', currencySymbol: 'zł', multiplier: 100, type: 'STRIPE' },
  { label: 'PYG', currencySymbol: '₲', multiplier: 1, type: 'STRIPE' },
  { label: 'QAR', currencySymbol: 'ر.ق', multiplier: 100, type: 'STRIPE' },
  { label: 'RON', currencySymbol: 'lei', multiplier: 100, type: 'STRIPE' },
  { label: 'RSD', currencySymbol: 'дин', multiplier: 100, type: 'STRIPE' },
  { label: 'RUB', currencySymbol: '₽', multiplier: 100, type: 'STRIPE' },
  { label: 'RWF', currencySymbol: 'Fr', multiplier: 1, type: 'STRIPE' },
  { label: 'SAR', currencySymbol: 'ر.س', multiplier: 100, type: 'STRIPE' },
  { label: 'SBD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'SCR', currencySymbol: '₨', multiplier: 100, type: 'STRIPE' },
  { label: 'SEK', currencySymbol: 'kr', multiplier: 100, type: 'STRIPE' },
  { label: 'SGD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'SHP', currencySymbol: '£', multiplier: 100, type: 'STRIPE' },
  { label: 'SLL', currencySymbol: 'Le', multiplier: 100, type: 'STRIPE' },
  { label: 'SOS', currencySymbol: 'Sh', multiplier: 100, type: 'STRIPE' },
  { label: 'SRD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'STD', currencySymbol: 'Db', multiplier: 100, type: 'STRIPE' },
  { label: 'SZL', currencySymbol: 'L', multiplier: 100, type: 'STRIPE' },
  { label: 'THB', currencySymbol: '฿', multiplier: 100, type: 'STRIPE' },
  { label: 'TJS', currencySymbol: 'ЅМ', multiplier: 100, type: 'STRIPE' },
  { label: 'TOP', currencySymbol: 'T$', multiplier: 100, type: 'STRIPE' },
  { label: 'TRY', currencySymbol: '₺', multiplier: 100, type: 'STRIPE' },
  { label: 'TTD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'TWD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'TZS', currencySymbol: 'Sh', multiplier: 100, type: 'STRIPE' },
  { label: 'UAH', currencySymbol: '₴', multiplier: 100, type: 'STRIPE' },
  { label: 'UGX', currencySymbol: 'Sh', multiplier: 1, type: 'STRIPE' },
  { label: 'UYU', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'UZS', currencySymbol: 'сўм', multiplier: 100, type: 'STRIPE' },
  { label: 'VND', currencySymbol: '₫', multiplier: 1, type: 'STRIPE' },
  { label: 'VUV', currencySymbol: 'Vt', multiplier: 1, type: 'STRIPE' },
  { label: 'WST', currencySymbol: 'T', multiplier: 100, type: 'STRIPE' },
  { label: 'XAF', currencySymbol: 'Fr', multiplier: 1, type: 'STRIPE' },
  { label: 'XCD', currencySymbol: '$', multiplier: 100, type: 'STRIPE' },
  { label: 'XOF', currencySymbol: 'Fr', multiplier: 1, type: 'STRIPE' },
  { label: 'XPF', currencySymbol: '₣', multiplier: 1, type: 'STRIPE' },
  { label: 'YER', currencySymbol: '﷼', multiplier: 100, type: 'STRIPE' },
  { label: 'ZAR', currencySymbol: 'Rs', multiplier: 100, type: 'STRIPE' },
  { label: 'ZMW', currencySymbol: 'ZK', multiplier: 100, type: 'STRIPE' },
];

export const paypalCurrencies = [
  { label: 'AUD', currencySymbol: '$', type: 'PAYPAL' },
  { label: 'BRL', currencySymbol: 'R$', type: 'PAYPAL' },
  { label: 'CAD', currencySymbol: '$', type: 'PAYPAL' },
  { label: 'CZK', currencySymbol: 'Kč', type: 'PAYPAL' },
  { label: 'DKK', currencySymbol: 'kr', type: 'PAYPAL' },
  { label: 'EUR', currencySymbol: '€', type: 'PAYPAL' },
  { label: 'HKD', currencySymbol: '$', type: 'PAYPAL' },
  { label: 'HUF', currencySymbol: 'Ft', type: 'PAYPAL' },
  { label: 'INR', currencySymbol: '₹', type: 'PAYPAL' },
  { label: 'ILS', currencySymbol: 'ع.د', type: 'PAYPAL' },
  { label: 'JPY', currencySymbol: '¥', type: 'PAYPAL' },
  { label: 'MYR', currencySymbol: 'RM', type: 'PAYPAL' },
  { label: 'MXN', currencySymbol: '$', type: 'PAYPAL' },
  { label: 'TWD', currencySymbol: '$', type: 'PAYPAL' },
  { label: 'NZD', currencySymbol: '$', type: 'PAYPAL' },
  { label: 'NOK', currencySymbol: 'kr', type: 'PAYPAL' },
  { label: 'PHP', currencySymbol: '₱', type: 'PAYPAL' },
  { label: 'PLN', currencySymbol: 'zł', type: 'PAYPAL' },
  { label: 'GBP', currencySymbol: '£', type: 'PAYPAL' },
  { label: 'RUB', currencySymbol: '₽', type: 'PAYPAL' },
  { label: 'SGD', currencySymbol: '$', type: 'PAYPAL' },
  { label: 'SEK', currencySymbol: 'kr', type: 'PAYPAL' },
  { label: 'CHF', currencySymbol: 'Fr', type: 'PAYPAL' },
  { label: 'THB', currencySymbol: '฿', type: 'PAYPAL' },
  { label: 'USD', currencySymbol: '$', type: 'PAYPAL' },
];
